/*
직원관리
*/
CREATE TABLE TB_EMPLOYEE
(
    EMP_ID INT IDENTITY(1,1) PRIMARY KEY,

    EMP_NO VARCHAR(20) NOT NULL UNIQUE,

    LOGIN_ID VARCHAR(50) NOT NULL UNIQUE,

    PASSWORD VARCHAR(255) NOT NULL,

    EMP_NAME NVARCHAR(100) NOT NULL,

    DEPT_CD VARCHAR(20) NOT NULL,

    POSITION_CD VARCHAR(20) NOT NULL,

    DUTY_CD VARCHAR(20),

    PHONE VARCHAR(20),

    EMAIL VARCHAR(100),

    ZIP_CODE VARCHAR(10),

    ADDRESS1 NVARCHAR(200),

    ADDRESS2 NVARCHAR(200),

    BIRTH_DATE DATE,

    JOIN_DATE DATE NOT NULL,

    RETIRE_DATE DATE,

    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    DEVICE_ID VARCHAR(100),

    COMPANY_ID VARCHAR(50) NOT NULL,

    LOC_CODE VARCHAR(50) NOT NULL,

    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',

    REMARK NVARCHAR(500),

    REG_ID VARCHAR(30) NOT NULL,

    REG_DATE DATETIME NOT NULL DEFAULT GETDATE(),

    UPD_ID VARCHAR(30),

    UPD_DATE DATETIME
);


/*
부서관리
*/
CREATE TABLE TB_DEPARTMENT
(
    DEPT_CD      VARCHAR(20) PRIMARY KEY,
    DEPT_NAME    NVARCHAR(100) NOT NULL,
    PARENT_CD    VARCHAR(20),
    SORT_NO      INT DEFAULT 0,
    USE_YN       CHAR(1) DEFAULT 'Y',
    REG_DATE     DATETIME DEFAULT GETDATE()
);

/*
직급관리
*/
CREATE TABLE TB_POSITION
(
    POSITION_CD    VARCHAR(20) PRIMARY KEY,
    POSITION_NAME  NVARCHAR(100),
    SORT_NO INT DEFAULT 0,
    USE_YN CHAR(1) DEFAULT 'Y'
);


/*
직책관리
*/
CREATE TABLE TB_DUTY
(
    DUTY_CD VARCHAR(20) PRIMARY KEY,
    DUTY_NAME NVARCHAR(100),
    SORT_NO INT DEFAULT 0,
    USE_YN CHAR(1) DEFAULT 'Y'
);

/*
장치관리
*/
USE [LCX]
GO

/****** 개체: Table [dbo].[TB_DEVICE] 스크립트 날짜: 2026-07-29 오후 2:55:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_DEVICE](
	[DEVICE_ID] [varchar](200) NOT NULL,
	[EMP_ID] [int] NOT NULL,
	[LOGIN_ID] [varchar](20) NOT NULL,
	[DEVICE_NAME] [varchar](200) NULL,
	[DEVICE_TYPE] [varchar](30) NULL,
	[PHONE_HASH] [varchar](50) NULL,
	[STATUS] [varchar](10) NULL,
	[REG_DATE] [datetime] NULL,
	[APPROVED_DATE] [datetime] NULL,
 CONSTRAINT [PK_TB_DEVICE] PRIMARY KEY CLUSTERED 
(
	[DEVICE_ID] ASC,
	[EMP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_DEVICE] ADD  CONSTRAINT [DF_TB_DEVICE_EMP_ID]  DEFAULT ((1)) FOR [EMP_ID]
GO

ALTER TABLE [dbo].[TB_DEVICE] ADD  CONSTRAINT [DF__TB_DEVICE__APPRO__7849DB76]  DEFAULT ('P') FOR [STATUS]
GO

ALTER TABLE [dbo].[TB_DEVICE] ADD  CONSTRAINT [DF__TB_DEVICE__REGIS__793DFFAF]  DEFAULT (getdate()) FOR [REG_DATE]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TB_DEVICE', @level2type=N'COLUMN',@level2name=N'DEVICE_ID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'A : ANDROID / I : IOS / W : WEB' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TB_DEVICE', @level2type=N'COLUMN',@level2name=N'DEVICE_TYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'IMEI 대체' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TB_DEVICE', @level2type=N'COLUMN',@level2name=N'PHONE_HASH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'P:PENDING / A:APPROVED / R:REJECTED' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TB_DEVICE', @level2type=N'COLUMN',@level2name=N'STATUS'
GO




CREATE TABLE TB_EMPLOYEE_HISTORY
(
    HISTORY_ID INT IDENTITY(1,1)
        PRIMARY KEY,


    EMP_ID INT NOT NULL,


    HISTORY_TYPE VARCHAR(30) NOT NULL,


    BEFORE_DATA NVARCHAR(MAX),

    AFTER_DATA NVARCHAR(MAX),


    REG_ID VARCHAR(30),

    REG_DATE DATETIME DEFAULT GETDATE()

)


CREATE TABLE TB_EMPLOYEE_FILE
(
    FILE_ID INT IDENTITY(1,1)
        PRIMARY KEY,


    EMP_ID INT NOT NULL,


    FILE_TYPE VARCHAR(20),
    

    ORG_FILE_NAME VARCHAR(200),

    SAVE_FILE_NAME VARCHAR(200),

    FILE_PATH VARCHAR(500),


    REG_ID VARCHAR(30),

    REG_DATE DATETIME DEFAULT GETDATE()

)

CREATE TABLE TB_AUDIT_LOG
(

    AUDIT_ID BIGINT IDENTITY(1,1)
        PRIMARY KEY,


    USER_ID VARCHAR(30),


    ACTION_TYPE VARCHAR(50),


    TARGET_TABLE VARCHAR(50),


    TARGET_ID VARCHAR(50),


    DESCRIPTION NVARCHAR(MAX),


    REG_DATE DATETIME DEFAULT GETDATE()

)