/*
직원관리
*/
CREATE TABLE TB_EMPLOYEE
(
    EMP_ID INT IDENTITY(1,1) PRIMARY KEY,

    EMP_NO VARCHAR(20) NOT NULL UNIQUE,

    LOGIN_ID VARCHAR(50) NOT NULL UNIQUE,

    PASSWORD VARCHAR(255) NOT NULL,

    EMP_NAME NVARCHAR(100) NOT NULL,

    DEPT_CD VARCHAR(20) NOT NULL,

    POSITION_CD VARCHAR(20) NOT NULL,

    DUTY_CD VARCHAR(20),

    PHONE VARCHAR(20),

    EMAIL VARCHAR(100),

    ZIP_CODE VARCHAR(10),

    ADDRESS1 NVARCHAR(200),

    ADDRESS2 NVARCHAR(200),

    BIRTH_DATE DATE,

    JOIN_DATE DATE NOT NULL,

    RETIRE_DATE DATE,

    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    DEVICE_ID VARCHAR(100),

    COMPANY_ID VARCHAR(50) NOT NULL,

    LOC_CODE VARCHAR(50) NOT NULL,

    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',

    REMARK NVARCHAR(500),

    REG_ID VARCHAR(30) NOT NULL,

    REG_DATE DATETIME NOT NULL DEFAULT GETDATE(),

    UPD_ID VARCHAR(30),

    UPD_DATE DATETIME
);


/*
부서관리
*/
CREATE TABLE TB_DEPARTMENT
(
    DEPT_CD      VARCHAR(20) PRIMARY KEY,
    DEPT_NAME    NVARCHAR(100) NOT NULL,
    PARENT_CD    VARCHAR(20),
    SORT_NO      INT DEFAULT 0,
    USE_YN       CHAR(1) DEFAULT 'Y',
    REG_DATE     DATETIME DEFAULT GETDATE()
);

/*
직급관리
*/
CREATE TABLE TB_POSITION
(
    POSITION_CD    VARCHAR(20) PRIMARY KEY,
    POSITION_NAME  NVARCHAR(100),
    SORT_NO INT DEFAULT 0,
    USE_YN CHAR(1) DEFAULT 'Y'
);

/*
직책관리
*/
CREATE TABLE TB_DUTY
(
    DUTY_CD VARCHAR(20) PRIMARY KEY,
    DUTY_NAME NVARCHAR(100),
    SORT_NO INT DEFAULT 0,
    USE_YN CHAR(1) DEFAULT 'Y'
);

/*
장치관리
*/
CREATE TABLE TB_DEVICE(
	DEVICE_ID   varchar(200)    PRIMARY KEY,
	EMP_ID  int PRIMARY KEY,
	LOGIN_ID    varchar(20)    NOT NULL,
	DEVICE_NAME varchar(200)   NULL,
	DEVICE_TYPE varchar(30)    NULL,
	PHONE_HASH  varchar(50)    NULL,
	[STATUS]    varchar(10)    NULL,
	REG_DATE datetime    NULL,
	APPROVED_DATE datetime    NULL
);

select *
from TB_DEPARTMENT


INSERT INTO TB_DEPARTMENT VALUES
('1000','대표이사',NULL,1,'Y',GETDATE()),
('1100','경영지원','1000',2,'Y',GETDATE()),
('1200','연구부서','1000',3,'Y',GETDATE()),
('1300','물류부서','1000',4,'Y',GETDATE());

INSERT INTO TB_POSITION VALUES
('P01','사원',1,'Y'),
('P02','주임',2,'Y'),
('P03','대리',3,'Y'),
('P04','과장',4,'Y'),
('P05','차장',5,'Y'),
('P06','부장',6,'Y'),
('P07','이사',7,'Y');

INSERT INTO TB_DUTY VALUES
('D01','팀원',1,'Y'),
('D02','팀장',2,'Y'),
('D03','실장',3,'Y'),
('D04','임원',4,'Y'),
('D05','대표',5,'Y');
